services:
  radio-analytics:
    build: .
    image: ${CONTAINER_REGISTRY_REPO}/radio-analytics:latest
    container_name: radio-analytics
    ports:
      - "8081:8081"
    restart: unless-stopped
    env_file:
      - .env