name: radio-analytics-default

services:
  radio-analytics:
    build: .
    image: ${CONTAINER_REGISTRY_REPO}/radio-analytics:latest
    container_name: radio-analytics
    restart: unless-stopped
    networks:
      - radio-net
    env_file:
      - .env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092