spring:
  application:
    name: ${SPRING_APP_NAME:radio-analytics}

  profiles:
    active: ${PROFILE_ACTIVE:default}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}

    properties:
      hibernate:
        default_schema: ${HIBERNATE_DEFAULT_SCHEMA:radio_analytics}
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        default_batch_fetch_size: ${HIBERNATE_DEFAULT_BATCH_FETCH_SIZE:20}

    show-sql: ${JPA_SHOW_SQL:true}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: radio-analytics
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: ${EXPOSURE_INCLUDE}

  endpoint:
    health:
      show-details: ${SHOW_DETAILS}

  metrics:
    tags:
      application: ${SPRING_APP_NAME:radio-analytics}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

server:
  port: ${SERVER_PORT:8081}

kafka:
  consumer:
    retry:
      generic-error-interval: 5000
      generic-error-max-retries: 3
      infrastructure-error-initial-interval: 5000
      infrastructure-error-multiplier: 2.0
      infrastructure-error-max-interval: 300000