spring:
  application:
    name: ${SPRING_APP_NAME:radio-analytics}
  profiles:
    active: ${PROFILE_ACTIVE:default}
  datasource:
    url: ${DB_URL}?currentSchema=${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}
    properties:
      hibernate:
        default_schema: ${HIBERNATE_DEFAULT_SCHEMA:radio_analytics}
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        default_batch_fetch_size: ${HIBERNATE_DEFAULT_BATCH_FETCH_SIZE:20}
    show-sql: ${JPA_SHOW_SQL:true}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: radio-analytics
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      observation-enabled: true

kafka:
  consumer:
    retry:
      generic-error:
        interval: ${KAFKA_CONSUMER_RETRY_GENERIC_ERROR_INTERVAL:5000}
        max-retries: ${KAFKA_CONSUMER_RETRY_GENERIC_ERROR_MAX_RETRIES:3}
      infrastructure-error:
        initial-interval: ${KAFKA_CONSUMER_RETRY_INFRASTRUCTURE_ERROR_INITIAL_INTERVAL:5000}
        multiplier: ${KAFKA_CONSUMER_RETRY_INFRASTRUCTURE_ERROR_MULTIPLIER:2.0}
        max-interval: ${KAFKA_CONSUMER_RETRY_INFRASTRUCTURE_ERROR_MAX_INTERVAL:300000}
    dlt:
      topics: organization-events-dlt,department-events-dlt,device-type-events-dlt,device-events-dlt

management:
  endpoints:
    web:
      exposure:
        include: ${EXPOSURE_INCLUDE}
  endpoint:
    health:
      show-details: ${SHOW_DETAILS}
  metrics:
    tags:
      application: ${SPRING_APP_NAME:radio-analytics}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: ${MANAGEMENT_OTLP_METRICS_ENDPOINT}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${MANAGEMENT_OTLP_TRACES_ENDPOINT}

logging:
#  pattern:
#    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  structured:
    format:
      console: logstash

analytics:
  realtime:
    deadline:
      seconds: ${ANALYTICS_REALTIME_DEADLINE_SECONDS:5}
  report:
    deadline:
      minutes: ${ANALYTICS_REPORT_DEADLINE_MINUTES:120}
    job:
      cron: ${ANALYTICS_REPORT_JOB_CRON:0 0 1 * * *}

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}